// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package notification

import (
	"github.com/blog/blog-community/internal/ent"
	"github.com/blog/blog-community/internal/notification/application"
	"github.com/blog/blog-community/internal/notification/delivery"
	"github.com/blog/blog-community/internal/notification/infrastructure"
)

// Injectors from wire.go:

// InitializeHandler injects notification dependencies.
func InitializeHandler(client *ent.Client) *delivery.NotificationHandler {
	repository := infrastructure.NewEntNotificationRepo(client)
	useCase := application.NewNotificationUseCase(repository)
	notificationHandler := delivery.NewNotificationHandler(useCase)
	return notificationHandler
}

// InitializeUseCase injects notification usecase only.
func InitializeUseCase(client *ent.Client) application.UseCase {
	repository := infrastructure.NewEntNotificationRepo(client)
	useCase := application.NewNotificationUseCase(repository)
	return useCase
}
