// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package post

import (
	"github.com/blog/blog-community/internal/ent"
	"github.com/blog/blog-community/internal/post/application"
	"github.com/blog/blog-community/internal/post/delivery"
	"github.com/blog/blog-community/internal/post/infrastructure"
	"github.com/blog/blog-community/pkg/search"
	"github.com/redis/go-redis/v9"
)

// Injectors from wire.go:

// InitializeHandler wires all dependencies for the post HTTP handler.
func InitializeHandler(client *ent.Client, redisClient *redis.Client, esClient *search.Client) *delivery.PostHandler {
	postRepository := infrastructure.NewEntPostRepo(client)
	searchTrendRepo := infrastructure.NewSearchTrendRepo(redisClient)
	postIndexer := infrastructure.NewPostIndexer(esClient, client)
	useCase := application.NewPostUseCase(postRepository, searchTrendRepo, postIndexer)
	postHandler := delivery.NewPostHandler(useCase)
	return postHandler
}
