// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package post

import (
	"github.com/blog/blog-community/internal/ent"
	"github.com/blog/blog-community/internal/post/application"
	"github.com/blog/blog-community/internal/post/delivery"
	"github.com/blog/blog-community/internal/post/infrastructure"
)

// Injectors from wire.go:

// InitializeHandler wires all dependencies for the post HTTP handler.
func InitializeHandler(client *ent.Client) *delivery.PostHandler {
	postRepository := infrastructure.NewEntPostRepo(client)
	useCase := application.NewPostUseCase(postRepository)
	postHandler := delivery.NewPostHandler(useCase)
	return postHandler
}
