// Code generated by ent, DO NOT EDIT.

package likerecord

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the likerecord type in the database.
	Label = "like_record"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTargetType holds the string denoting the target_type field in the database.
	FieldTargetType = "target_type"
	// FieldTargetID holds the string denoting the target_id field in the database.
	FieldTargetID = "target_id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the likerecord in the database.
	Table = "like_records"
)

// Columns holds all SQL columns for likerecord fields.
var Columns = []string{
	FieldID,
	FieldTargetType,
	FieldTargetID,
	FieldUserID,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// TargetType defines the type for the "target_type" enum field.
type TargetType string

// TargetType values.
const (
	TargetTypePost    TargetType = "post"
	TargetTypeComment TargetType = "comment"
)

func (tt TargetType) String() string {
	return string(tt)
}

// TargetTypeValidator is a validator for the "target_type" field enum values. It is called by the builders before save.
func TargetTypeValidator(tt TargetType) error {
	switch tt {
	case TargetTypePost, TargetTypeComment:
		return nil
	default:
		return fmt.Errorf("likerecord: invalid enum value for target_type field: %q", tt)
	}
}

// OrderOption defines the ordering options for the LikeRecord queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTargetType orders the results by the target_type field.
func ByTargetType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTargetType, opts...).ToFunc()
}

// ByTargetID orders the results by the target_id field.
func ByTargetID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTargetID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
