// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// CollectRecordsColumns holds the columns for the "collect_records" table.
	CollectRecordsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true},
		{Name: "target_type", Type: field.TypeEnum, Enums: []string{"post"}},
		{Name: "target_id", Type: field.TypeUint64},
		{Name: "user_id", Type: field.TypeUint64},
		{Name: "created_at", Type: field.TypeTime},
	}
	// CollectRecordsTable holds the schema information for the "collect_records" table.
	CollectRecordsTable = &schema.Table{
		Name:       "collect_records",
		Columns:    CollectRecordsColumns,
		PrimaryKey: []*schema.Column{CollectRecordsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "collectrecord_target_type_target_id_user_id",
				Unique:  true,
				Columns: []*schema.Column{CollectRecordsColumns[1], CollectRecordsColumns[2], CollectRecordsColumns[3]},
			},
			{
				Name:    "collectrecord_user_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{CollectRecordsColumns[3], CollectRecordsColumns[4]},
			},
		},
	}
	// CommentsColumns holds the columns for the "comments" table.
	CommentsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true},
		{Name: "content", Type: field.TypeString, Size: 2147483647},
		{Name: "post_id", Type: field.TypeUint64},
		{Name: "author_id", Type: field.TypeUint64},
		{Name: "parent_id", Type: field.TypeUint64, Nullable: true},
		{Name: "like_count", Type: field.TypeInt, Default: 0},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// CommentsTable holds the schema information for the "comments" table.
	CommentsTable = &schema.Table{
		Name:       "comments",
		Columns:    CommentsColumns,
		PrimaryKey: []*schema.Column{CommentsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "comment_post_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{CommentsColumns[2], CommentsColumns[6]},
			},
			{
				Name:    "comment_parent_id",
				Unique:  false,
				Columns: []*schema.Column{CommentsColumns[4]},
			},
		},
	}
	// LikeRecordsColumns holds the columns for the "like_records" table.
	LikeRecordsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true},
		{Name: "target_type", Type: field.TypeEnum, Enums: []string{"post", "comment"}},
		{Name: "target_id", Type: field.TypeUint64},
		{Name: "user_id", Type: field.TypeUint64},
		{Name: "created_at", Type: field.TypeTime},
	}
	// LikeRecordsTable holds the schema information for the "like_records" table.
	LikeRecordsTable = &schema.Table{
		Name:       "like_records",
		Columns:    LikeRecordsColumns,
		PrimaryKey: []*schema.Column{LikeRecordsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "likerecord_target_type_target_id_user_id",
				Unique:  true,
				Columns: []*schema.Column{LikeRecordsColumns[1], LikeRecordsColumns[2], LikeRecordsColumns[3]},
			},
			{
				Name:    "likerecord_user_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{LikeRecordsColumns[3], LikeRecordsColumns[4]},
			},
		},
	}
	// PostsColumns holds the columns for the "posts" table.
	PostsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true},
		{Name: "title", Type: field.TypeString, Size: 256},
		{Name: "content", Type: field.TypeString, Size: 2147483647},
		{Name: "summary", Type: field.TypeString, Nullable: true, Size: 512},
		{Name: "content_type", Type: field.TypeEnum, Enums: []string{"markdown", "rich_text"}, Default: "markdown"},
		{Name: "cover_image", Type: field.TypeString, Nullable: true, Size: 512},
		{Name: "author_id", Type: field.TypeUint64},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"draft", "pending", "published", "rejected"}, Default: "draft"},
		{Name: "view_count", Type: field.TypeInt, Default: 0},
		{Name: "like_count", Type: field.TypeInt, Default: 0},
		{Name: "comment_count", Type: field.TypeInt, Default: 0},
		{Name: "collect_count", Type: field.TypeInt, Default: 0},
		{Name: "tags", Type: field.TypeJSON, Nullable: true},
		{Name: "published_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// PostsTable holds the schema information for the "posts" table.
	PostsTable = &schema.Table{
		Name:       "posts",
		Columns:    PostsColumns,
		PrimaryKey: []*schema.Column{PostsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "post_author_id",
				Unique:  false,
				Columns: []*schema.Column{PostsColumns[6]},
			},
			{
				Name:    "post_status_created_at",
				Unique:  false,
				Columns: []*schema.Column{PostsColumns[7], PostsColumns[14]},
			},
			{
				Name:    "post_status_like_count_created_at",
				Unique:  false,
				Columns: []*schema.Column{PostsColumns[7], PostsColumns[9], PostsColumns[14]},
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true},
		{Name: "email", Type: field.TypeString, Unique: true, Size: 128},
		{Name: "username", Type: field.TypeString, Unique: true, Size: 64},
		{Name: "password_hash", Type: field.TypeString, Nullable: true},
		{Name: "avatar_url", Type: field.TypeString, Nullable: true, Size: 512},
		{Name: "oauth_provider", Type: field.TypeEnum, Enums: []string{"none", "github", "google"}, Default: "none"},
		{Name: "oauth_id", Type: field.TypeString, Nullable: true},
		{Name: "role", Type: field.TypeString, Default: "user"},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "user_oauth_provider_oauth_id",
				Unique:  true,
				Columns: []*schema.Column{UsersColumns[5], UsersColumns[6]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		CollectRecordsTable,
		CommentsTable,
		LikeRecordsTable,
		PostsTable,
		UsersTable,
	}
)

func init() {
}
