// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package user

import (
	"github.com/blog/blog-community/configs"
	"github.com/blog/blog-community/internal/ent"
	"github.com/blog/blog-community/internal/user/application"
	"github.com/blog/blog-community/internal/user/delivery"
	"github.com/blog/blog-community/internal/user/infrastructure"
	"github.com/blog/blog-community/pkg/auth"
	"github.com/blog/blog-community/pkg/database"
)

// Injectors from wire.go:

// InitializeServer wires all dependencies for the user HTTP server.
func InitializeServer(cfg *configs.Config, client *ent.Client, store auth.TokenStore) *delivery.Server {
	userRepository := infrastructure.NewEntUserRepo(client)
	entTransactor := database.NewEntTransactor(client)
	useCase := application.NewUserUseCase(userRepository, entTransactor)
	userHandler := delivery.NewUserHandlerFromConfig(useCase, cfg, store)
	oAuthHandler := delivery.NewOAuthHandlerFromConfig(useCase, cfg, store)
	server := delivery.NewServer(userHandler, oAuthHandler)
	return server
}
