// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/blog/blog-community/internal/ent/collectrecord"
	"github.com/blog/blog-community/internal/ent/predicate"
)

// CollectRecordUpdate is the builder for updating CollectRecord entities.
type CollectRecordUpdate struct {
	config
	hooks    []Hook
	mutation *CollectRecordMutation
}

// Where appends a list predicates to the CollectRecordUpdate builder.
func (_u *CollectRecordUpdate) Where(ps ...predicate.CollectRecord) *CollectRecordUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTargetType sets the "target_type" field.
func (_u *CollectRecordUpdate) SetTargetType(v collectrecord.TargetType) *CollectRecordUpdate {
	_u.mutation.SetTargetType(v)
	return _u
}

// SetNillableTargetType sets the "target_type" field if the given value is not nil.
func (_u *CollectRecordUpdate) SetNillableTargetType(v *collectrecord.TargetType) *CollectRecordUpdate {
	if v != nil {
		_u.SetTargetType(*v)
	}
	return _u
}

// SetTargetID sets the "target_id" field.
func (_u *CollectRecordUpdate) SetTargetID(v uint64) *CollectRecordUpdate {
	_u.mutation.ResetTargetID()
	_u.mutation.SetTargetID(v)
	return _u
}

// SetNillableTargetID sets the "target_id" field if the given value is not nil.
func (_u *CollectRecordUpdate) SetNillableTargetID(v *uint64) *CollectRecordUpdate {
	if v != nil {
		_u.SetTargetID(*v)
	}
	return _u
}

// AddTargetID adds value to the "target_id" field.
func (_u *CollectRecordUpdate) AddTargetID(v int64) *CollectRecordUpdate {
	_u.mutation.AddTargetID(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *CollectRecordUpdate) SetUserID(v uint64) *CollectRecordUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *CollectRecordUpdate) SetNillableUserID(v *uint64) *CollectRecordUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *CollectRecordUpdate) AddUserID(v int64) *CollectRecordUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// Mutation returns the CollectRecordMutation object of the builder.
func (_u *CollectRecordUpdate) Mutation() *CollectRecordMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CollectRecordUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CollectRecordUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CollectRecordUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CollectRecordUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CollectRecordUpdate) check() error {
	if v, ok := _u.mutation.TargetType(); ok {
		if err := collectrecord.TargetTypeValidator(v); err != nil {
			return &ValidationError{Name: "target_type", err: fmt.Errorf(`ent: validator failed for field "CollectRecord.target_type": %w`, err)}
		}
	}
	return nil
}

func (_u *CollectRecordUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(collectrecord.Table, collectrecord.Columns, sqlgraph.NewFieldSpec(collectrecord.FieldID, field.TypeUint64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TargetType(); ok {
		_spec.SetField(collectrecord.FieldTargetType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.TargetID(); ok {
		_spec.SetField(collectrecord.FieldTargetID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedTargetID(); ok {
		_spec.AddField(collectrecord.FieldTargetID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(collectrecord.FieldUserID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(collectrecord.FieldUserID, field.TypeUint64, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{collectrecord.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CollectRecordUpdateOne is the builder for updating a single CollectRecord entity.
type CollectRecordUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CollectRecordMutation
}

// SetTargetType sets the "target_type" field.
func (_u *CollectRecordUpdateOne) SetTargetType(v collectrecord.TargetType) *CollectRecordUpdateOne {
	_u.mutation.SetTargetType(v)
	return _u
}

// SetNillableTargetType sets the "target_type" field if the given value is not nil.
func (_u *CollectRecordUpdateOne) SetNillableTargetType(v *collectrecord.TargetType) *CollectRecordUpdateOne {
	if v != nil {
		_u.SetTargetType(*v)
	}
	return _u
}

// SetTargetID sets the "target_id" field.
func (_u *CollectRecordUpdateOne) SetTargetID(v uint64) *CollectRecordUpdateOne {
	_u.mutation.ResetTargetID()
	_u.mutation.SetTargetID(v)
	return _u
}

// SetNillableTargetID sets the "target_id" field if the given value is not nil.
func (_u *CollectRecordUpdateOne) SetNillableTargetID(v *uint64) *CollectRecordUpdateOne {
	if v != nil {
		_u.SetTargetID(*v)
	}
	return _u
}

// AddTargetID adds value to the "target_id" field.
func (_u *CollectRecordUpdateOne) AddTargetID(v int64) *CollectRecordUpdateOne {
	_u.mutation.AddTargetID(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *CollectRecordUpdateOne) SetUserID(v uint64) *CollectRecordUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *CollectRecordUpdateOne) SetNillableUserID(v *uint64) *CollectRecordUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *CollectRecordUpdateOne) AddUserID(v int64) *CollectRecordUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// Mutation returns the CollectRecordMutation object of the builder.
func (_u *CollectRecordUpdateOne) Mutation() *CollectRecordMutation {
	return _u.mutation
}

// Where appends a list predicates to the CollectRecordUpdate builder.
func (_u *CollectRecordUpdateOne) Where(ps ...predicate.CollectRecord) *CollectRecordUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CollectRecordUpdateOne) Select(field string, fields ...string) *CollectRecordUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CollectRecord entity.
func (_u *CollectRecordUpdateOne) Save(ctx context.Context) (*CollectRecord, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CollectRecordUpdateOne) SaveX(ctx context.Context) *CollectRecord {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CollectRecordUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CollectRecordUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CollectRecordUpdateOne) check() error {
	if v, ok := _u.mutation.TargetType(); ok {
		if err := collectrecord.TargetTypeValidator(v); err != nil {
			return &ValidationError{Name: "target_type", err: fmt.Errorf(`ent: validator failed for field "CollectRecord.target_type": %w`, err)}
		}
	}
	return nil
}

func (_u *CollectRecordUpdateOne) sqlSave(ctx context.Context) (_node *CollectRecord, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(collectrecord.Table, collectrecord.Columns, sqlgraph.NewFieldSpec(collectrecord.FieldID, field.TypeUint64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CollectRecord.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, collectrecord.FieldID)
		for _, f := range fields {
			if !collectrecord.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != collectrecord.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TargetType(); ok {
		_spec.SetField(collectrecord.FieldTargetType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.TargetID(); ok {
		_spec.SetField(collectrecord.FieldTargetID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedTargetID(); ok {
		_spec.AddField(collectrecord.FieldTargetID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(collectrecord.FieldUserID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(collectrecord.FieldUserID, field.TypeUint64, value)
	}
	_node = &CollectRecord{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{collectrecord.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
