// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/blog/blog-community/internal/ent/collectrecord"
)

// CollectRecord is the model entity for the CollectRecord schema.
type CollectRecord struct {
	config `json:"-"`
	// ID of the ent.
	ID uint64 `json:"id,omitempty"`
	// TargetType holds the value of the "target_type" field.
	TargetType collectrecord.TargetType `json:"target_type,omitempty"`
	// TargetID holds the value of the "target_id" field.
	TargetID uint64 `json:"target_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID uint64 `json:"user_id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CollectRecord) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case collectrecord.FieldID, collectrecord.FieldTargetID, collectrecord.FieldUserID:
			values[i] = new(sql.NullInt64)
		case collectrecord.FieldTargetType:
			values[i] = new(sql.NullString)
		case collectrecord.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CollectRecord fields.
func (_m *CollectRecord) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case collectrecord.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = uint64(value.Int64)
		case collectrecord.FieldTargetType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field target_type", values[i])
			} else if value.Valid {
				_m.TargetType = collectrecord.TargetType(value.String)
			}
		case collectrecord.FieldTargetID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field target_id", values[i])
			} else if value.Valid {
				_m.TargetID = uint64(value.Int64)
			}
		case collectrecord.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = uint64(value.Int64)
			}
		case collectrecord.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CollectRecord.
// This includes values selected through modifiers, order, etc.
func (_m *CollectRecord) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this CollectRecord.
// Note that you need to call CollectRecord.Unwrap() before calling this method if this CollectRecord
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *CollectRecord) Update() *CollectRecordUpdateOne {
	return NewCollectRecordClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the CollectRecord entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *CollectRecord) Unwrap() *CollectRecord {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: CollectRecord is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *CollectRecord) String() string {
	var builder strings.Builder
	builder.WriteString("CollectRecord(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("target_type=")
	builder.WriteString(fmt.Sprintf("%v", _m.TargetType))
	builder.WriteString(", ")
	builder.WriteString("target_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TargetID))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// CollectRecords is a parsable slice of CollectRecord.
type CollectRecords []*CollectRecord
