// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/blog/blog-community/internal/ent/follow"
	"github.com/blog/blog-community/internal/ent/predicate"
)

// FollowUpdate is the builder for updating Follow entities.
type FollowUpdate struct {
	config
	hooks    []Hook
	mutation *FollowMutation
}

// Where appends a list predicates to the FollowUpdate builder.
func (_u *FollowUpdate) Where(ps ...predicate.Follow) *FollowUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetFollowerID sets the "follower_id" field.
func (_u *FollowUpdate) SetFollowerID(v uint64) *FollowUpdate {
	_u.mutation.ResetFollowerID()
	_u.mutation.SetFollowerID(v)
	return _u
}

// SetNillableFollowerID sets the "follower_id" field if the given value is not nil.
func (_u *FollowUpdate) SetNillableFollowerID(v *uint64) *FollowUpdate {
	if v != nil {
		_u.SetFollowerID(*v)
	}
	return _u
}

// AddFollowerID adds value to the "follower_id" field.
func (_u *FollowUpdate) AddFollowerID(v int64) *FollowUpdate {
	_u.mutation.AddFollowerID(v)
	return _u
}

// SetFollowingID sets the "following_id" field.
func (_u *FollowUpdate) SetFollowingID(v uint64) *FollowUpdate {
	_u.mutation.ResetFollowingID()
	_u.mutation.SetFollowingID(v)
	return _u
}

// SetNillableFollowingID sets the "following_id" field if the given value is not nil.
func (_u *FollowUpdate) SetNillableFollowingID(v *uint64) *FollowUpdate {
	if v != nil {
		_u.SetFollowingID(*v)
	}
	return _u
}

// AddFollowingID adds value to the "following_id" field.
func (_u *FollowUpdate) AddFollowingID(v int64) *FollowUpdate {
	_u.mutation.AddFollowingID(v)
	return _u
}

// Mutation returns the FollowMutation object of the builder.
func (_u *FollowUpdate) Mutation() *FollowMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *FollowUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FollowUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *FollowUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FollowUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *FollowUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(follow.Table, follow.Columns, sqlgraph.NewFieldSpec(follow.FieldID, field.TypeUint64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.FollowerID(); ok {
		_spec.SetField(follow.FieldFollowerID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedFollowerID(); ok {
		_spec.AddField(follow.FieldFollowerID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.FollowingID(); ok {
		_spec.SetField(follow.FieldFollowingID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedFollowingID(); ok {
		_spec.AddField(follow.FieldFollowingID, field.TypeUint64, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{follow.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// FollowUpdateOne is the builder for updating a single Follow entity.
type FollowUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *FollowMutation
}

// SetFollowerID sets the "follower_id" field.
func (_u *FollowUpdateOne) SetFollowerID(v uint64) *FollowUpdateOne {
	_u.mutation.ResetFollowerID()
	_u.mutation.SetFollowerID(v)
	return _u
}

// SetNillableFollowerID sets the "follower_id" field if the given value is not nil.
func (_u *FollowUpdateOne) SetNillableFollowerID(v *uint64) *FollowUpdateOne {
	if v != nil {
		_u.SetFollowerID(*v)
	}
	return _u
}

// AddFollowerID adds value to the "follower_id" field.
func (_u *FollowUpdateOne) AddFollowerID(v int64) *FollowUpdateOne {
	_u.mutation.AddFollowerID(v)
	return _u
}

// SetFollowingID sets the "following_id" field.
func (_u *FollowUpdateOne) SetFollowingID(v uint64) *FollowUpdateOne {
	_u.mutation.ResetFollowingID()
	_u.mutation.SetFollowingID(v)
	return _u
}

// SetNillableFollowingID sets the "following_id" field if the given value is not nil.
func (_u *FollowUpdateOne) SetNillableFollowingID(v *uint64) *FollowUpdateOne {
	if v != nil {
		_u.SetFollowingID(*v)
	}
	return _u
}

// AddFollowingID adds value to the "following_id" field.
func (_u *FollowUpdateOne) AddFollowingID(v int64) *FollowUpdateOne {
	_u.mutation.AddFollowingID(v)
	return _u
}

// Mutation returns the FollowMutation object of the builder.
func (_u *FollowUpdateOne) Mutation() *FollowMutation {
	return _u.mutation
}

// Where appends a list predicates to the FollowUpdate builder.
func (_u *FollowUpdateOne) Where(ps ...predicate.Follow) *FollowUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *FollowUpdateOne) Select(field string, fields ...string) *FollowUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Follow entity.
func (_u *FollowUpdateOne) Save(ctx context.Context) (*Follow, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FollowUpdateOne) SaveX(ctx context.Context) *Follow {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *FollowUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FollowUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *FollowUpdateOne) sqlSave(ctx context.Context) (_node *Follow, err error) {
	_spec := sqlgraph.NewUpdateSpec(follow.Table, follow.Columns, sqlgraph.NewFieldSpec(follow.FieldID, field.TypeUint64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Follow.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, follow.FieldID)
		for _, f := range fields {
			if !follow.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != follow.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.FollowerID(); ok {
		_spec.SetField(follow.FieldFollowerID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedFollowerID(); ok {
		_spec.AddField(follow.FieldFollowerID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.FollowingID(); ok {
		_spec.SetField(follow.FieldFollowingID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedFollowingID(); ok {
		_spec.AddField(follow.FieldFollowingID, field.TypeUint64, value)
	}
	_node = &Follow{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{follow.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
