// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/blog/blog-community/internal/ent/likerecord"
	"github.com/blog/blog-community/internal/ent/predicate"
)

// LikeRecordUpdate is the builder for updating LikeRecord entities.
type LikeRecordUpdate struct {
	config
	hooks    []Hook
	mutation *LikeRecordMutation
}

// Where appends a list predicates to the LikeRecordUpdate builder.
func (_u *LikeRecordUpdate) Where(ps ...predicate.LikeRecord) *LikeRecordUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTargetType sets the "target_type" field.
func (_u *LikeRecordUpdate) SetTargetType(v likerecord.TargetType) *LikeRecordUpdate {
	_u.mutation.SetTargetType(v)
	return _u
}

// SetNillableTargetType sets the "target_type" field if the given value is not nil.
func (_u *LikeRecordUpdate) SetNillableTargetType(v *likerecord.TargetType) *LikeRecordUpdate {
	if v != nil {
		_u.SetTargetType(*v)
	}
	return _u
}

// SetTargetID sets the "target_id" field.
func (_u *LikeRecordUpdate) SetTargetID(v uint64) *LikeRecordUpdate {
	_u.mutation.ResetTargetID()
	_u.mutation.SetTargetID(v)
	return _u
}

// SetNillableTargetID sets the "target_id" field if the given value is not nil.
func (_u *LikeRecordUpdate) SetNillableTargetID(v *uint64) *LikeRecordUpdate {
	if v != nil {
		_u.SetTargetID(*v)
	}
	return _u
}

// AddTargetID adds value to the "target_id" field.
func (_u *LikeRecordUpdate) AddTargetID(v int64) *LikeRecordUpdate {
	_u.mutation.AddTargetID(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *LikeRecordUpdate) SetUserID(v uint64) *LikeRecordUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *LikeRecordUpdate) SetNillableUserID(v *uint64) *LikeRecordUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *LikeRecordUpdate) AddUserID(v int64) *LikeRecordUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// Mutation returns the LikeRecordMutation object of the builder.
func (_u *LikeRecordUpdate) Mutation() *LikeRecordMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *LikeRecordUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LikeRecordUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *LikeRecordUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LikeRecordUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LikeRecordUpdate) check() error {
	if v, ok := _u.mutation.TargetType(); ok {
		if err := likerecord.TargetTypeValidator(v); err != nil {
			return &ValidationError{Name: "target_type", err: fmt.Errorf(`ent: validator failed for field "LikeRecord.target_type": %w`, err)}
		}
	}
	return nil
}

func (_u *LikeRecordUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(likerecord.Table, likerecord.Columns, sqlgraph.NewFieldSpec(likerecord.FieldID, field.TypeUint64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TargetType(); ok {
		_spec.SetField(likerecord.FieldTargetType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.TargetID(); ok {
		_spec.SetField(likerecord.FieldTargetID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedTargetID(); ok {
		_spec.AddField(likerecord.FieldTargetID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(likerecord.FieldUserID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(likerecord.FieldUserID, field.TypeUint64, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{likerecord.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// LikeRecordUpdateOne is the builder for updating a single LikeRecord entity.
type LikeRecordUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *LikeRecordMutation
}

// SetTargetType sets the "target_type" field.
func (_u *LikeRecordUpdateOne) SetTargetType(v likerecord.TargetType) *LikeRecordUpdateOne {
	_u.mutation.SetTargetType(v)
	return _u
}

// SetNillableTargetType sets the "target_type" field if the given value is not nil.
func (_u *LikeRecordUpdateOne) SetNillableTargetType(v *likerecord.TargetType) *LikeRecordUpdateOne {
	if v != nil {
		_u.SetTargetType(*v)
	}
	return _u
}

// SetTargetID sets the "target_id" field.
func (_u *LikeRecordUpdateOne) SetTargetID(v uint64) *LikeRecordUpdateOne {
	_u.mutation.ResetTargetID()
	_u.mutation.SetTargetID(v)
	return _u
}

// SetNillableTargetID sets the "target_id" field if the given value is not nil.
func (_u *LikeRecordUpdateOne) SetNillableTargetID(v *uint64) *LikeRecordUpdateOne {
	if v != nil {
		_u.SetTargetID(*v)
	}
	return _u
}

// AddTargetID adds value to the "target_id" field.
func (_u *LikeRecordUpdateOne) AddTargetID(v int64) *LikeRecordUpdateOne {
	_u.mutation.AddTargetID(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *LikeRecordUpdateOne) SetUserID(v uint64) *LikeRecordUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *LikeRecordUpdateOne) SetNillableUserID(v *uint64) *LikeRecordUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *LikeRecordUpdateOne) AddUserID(v int64) *LikeRecordUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// Mutation returns the LikeRecordMutation object of the builder.
func (_u *LikeRecordUpdateOne) Mutation() *LikeRecordMutation {
	return _u.mutation
}

// Where appends a list predicates to the LikeRecordUpdate builder.
func (_u *LikeRecordUpdateOne) Where(ps ...predicate.LikeRecord) *LikeRecordUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *LikeRecordUpdateOne) Select(field string, fields ...string) *LikeRecordUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated LikeRecord entity.
func (_u *LikeRecordUpdateOne) Save(ctx context.Context) (*LikeRecord, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LikeRecordUpdateOne) SaveX(ctx context.Context) *LikeRecord {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *LikeRecordUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LikeRecordUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LikeRecordUpdateOne) check() error {
	if v, ok := _u.mutation.TargetType(); ok {
		if err := likerecord.TargetTypeValidator(v); err != nil {
			return &ValidationError{Name: "target_type", err: fmt.Errorf(`ent: validator failed for field "LikeRecord.target_type": %w`, err)}
		}
	}
	return nil
}

func (_u *LikeRecordUpdateOne) sqlSave(ctx context.Context) (_node *LikeRecord, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(likerecord.Table, likerecord.Columns, sqlgraph.NewFieldSpec(likerecord.FieldID, field.TypeUint64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "LikeRecord.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, likerecord.FieldID)
		for _, f := range fields {
			if !likerecord.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != likerecord.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TargetType(); ok {
		_spec.SetField(likerecord.FieldTargetType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.TargetID(); ok {
		_spec.SetField(likerecord.FieldTargetID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedTargetID(); ok {
		_spec.AddField(likerecord.FieldTargetID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(likerecord.FieldUserID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(likerecord.FieldUserID, field.TypeUint64, value)
	}
	_node = &LikeRecord{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{likerecord.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
