// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/blog/blog-community/internal/ent/notification"
	"github.com/blog/blog-community/internal/ent/predicate"
)

// NotificationUpdate is the builder for updating Notification entities.
type NotificationUpdate struct {
	config
	hooks    []Hook
	mutation *NotificationMutation
}

// Where appends a list predicates to the NotificationUpdate builder.
func (_u *NotificationUpdate) Where(ps ...predicate.Notification) *NotificationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *NotificationUpdate) SetUserID(v uint64) *NotificationUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *NotificationUpdate) SetNillableUserID(v *uint64) *NotificationUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *NotificationUpdate) AddUserID(v int64) *NotificationUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetType sets the "type" field.
func (_u *NotificationUpdate) SetType(v notification.Type) *NotificationUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *NotificationUpdate) SetNillableType(v *notification.Type) *NotificationUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *NotificationUpdate) SetTitle(v string) *NotificationUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *NotificationUpdate) SetNillableTitle(v *string) *NotificationUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *NotificationUpdate) SetContent(v string) *NotificationUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *NotificationUpdate) SetNillableContent(v *string) *NotificationUpdate {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetActorID sets the "actor_id" field.
func (_u *NotificationUpdate) SetActorID(v uint64) *NotificationUpdate {
	_u.mutation.ResetActorID()
	_u.mutation.SetActorID(v)
	return _u
}

// SetNillableActorID sets the "actor_id" field if the given value is not nil.
func (_u *NotificationUpdate) SetNillableActorID(v *uint64) *NotificationUpdate {
	if v != nil {
		_u.SetActorID(*v)
	}
	return _u
}

// AddActorID adds value to the "actor_id" field.
func (_u *NotificationUpdate) AddActorID(v int64) *NotificationUpdate {
	_u.mutation.AddActorID(v)
	return _u
}

// ClearActorID clears the value of the "actor_id" field.
func (_u *NotificationUpdate) ClearActorID() *NotificationUpdate {
	_u.mutation.ClearActorID()
	return _u
}

// SetTargetID sets the "target_id" field.
func (_u *NotificationUpdate) SetTargetID(v uint64) *NotificationUpdate {
	_u.mutation.ResetTargetID()
	_u.mutation.SetTargetID(v)
	return _u
}

// SetNillableTargetID sets the "target_id" field if the given value is not nil.
func (_u *NotificationUpdate) SetNillableTargetID(v *uint64) *NotificationUpdate {
	if v != nil {
		_u.SetTargetID(*v)
	}
	return _u
}

// AddTargetID adds value to the "target_id" field.
func (_u *NotificationUpdate) AddTargetID(v int64) *NotificationUpdate {
	_u.mutation.AddTargetID(v)
	return _u
}

// ClearTargetID clears the value of the "target_id" field.
func (_u *NotificationUpdate) ClearTargetID() *NotificationUpdate {
	_u.mutation.ClearTargetID()
	return _u
}

// SetTargetType sets the "target_type" field.
func (_u *NotificationUpdate) SetTargetType(v string) *NotificationUpdate {
	_u.mutation.SetTargetType(v)
	return _u
}

// SetNillableTargetType sets the "target_type" field if the given value is not nil.
func (_u *NotificationUpdate) SetNillableTargetType(v *string) *NotificationUpdate {
	if v != nil {
		_u.SetTargetType(*v)
	}
	return _u
}

// ClearTargetType clears the value of the "target_type" field.
func (_u *NotificationUpdate) ClearTargetType() *NotificationUpdate {
	_u.mutation.ClearTargetType()
	return _u
}

// SetIsRead sets the "is_read" field.
func (_u *NotificationUpdate) SetIsRead(v bool) *NotificationUpdate {
	_u.mutation.SetIsRead(v)
	return _u
}

// SetNillableIsRead sets the "is_read" field if the given value is not nil.
func (_u *NotificationUpdate) SetNillableIsRead(v *bool) *NotificationUpdate {
	if v != nil {
		_u.SetIsRead(*v)
	}
	return _u
}

// SetReadAt sets the "read_at" field.
func (_u *NotificationUpdate) SetReadAt(v time.Time) *NotificationUpdate {
	_u.mutation.SetReadAt(v)
	return _u
}

// SetNillableReadAt sets the "read_at" field if the given value is not nil.
func (_u *NotificationUpdate) SetNillableReadAt(v *time.Time) *NotificationUpdate {
	if v != nil {
		_u.SetReadAt(*v)
	}
	return _u
}

// ClearReadAt clears the value of the "read_at" field.
func (_u *NotificationUpdate) ClearReadAt() *NotificationUpdate {
	_u.mutation.ClearReadAt()
	return _u
}

// Mutation returns the NotificationMutation object of the builder.
func (_u *NotificationUpdate) Mutation() *NotificationMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *NotificationUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NotificationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *NotificationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NotificationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *NotificationUpdate) check() error {
	if v, ok := _u.mutation.GetType(); ok {
		if err := notification.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Notification.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Title(); ok {
		if err := notification.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Notification.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TargetType(); ok {
		if err := notification.TargetTypeValidator(v); err != nil {
			return &ValidationError{Name: "target_type", err: fmt.Errorf(`ent: validator failed for field "Notification.target_type": %w`, err)}
		}
	}
	return nil
}

func (_u *NotificationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(notification.Table, notification.Columns, sqlgraph.NewFieldSpec(notification.FieldID, field.TypeUint64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(notification.FieldUserID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(notification.FieldUserID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(notification.FieldType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(notification.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(notification.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.ActorID(); ok {
		_spec.SetField(notification.FieldActorID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedActorID(); ok {
		_spec.AddField(notification.FieldActorID, field.TypeUint64, value)
	}
	if _u.mutation.ActorIDCleared() {
		_spec.ClearField(notification.FieldActorID, field.TypeUint64)
	}
	if value, ok := _u.mutation.TargetID(); ok {
		_spec.SetField(notification.FieldTargetID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedTargetID(); ok {
		_spec.AddField(notification.FieldTargetID, field.TypeUint64, value)
	}
	if _u.mutation.TargetIDCleared() {
		_spec.ClearField(notification.FieldTargetID, field.TypeUint64)
	}
	if value, ok := _u.mutation.TargetType(); ok {
		_spec.SetField(notification.FieldTargetType, field.TypeString, value)
	}
	if _u.mutation.TargetTypeCleared() {
		_spec.ClearField(notification.FieldTargetType, field.TypeString)
	}
	if value, ok := _u.mutation.IsRead(); ok {
		_spec.SetField(notification.FieldIsRead, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ReadAt(); ok {
		_spec.SetField(notification.FieldReadAt, field.TypeTime, value)
	}
	if _u.mutation.ReadAtCleared() {
		_spec.ClearField(notification.FieldReadAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{notification.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// NotificationUpdateOne is the builder for updating a single Notification entity.
type NotificationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *NotificationMutation
}

// SetUserID sets the "user_id" field.
func (_u *NotificationUpdateOne) SetUserID(v uint64) *NotificationUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *NotificationUpdateOne) SetNillableUserID(v *uint64) *NotificationUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *NotificationUpdateOne) AddUserID(v int64) *NotificationUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetType sets the "type" field.
func (_u *NotificationUpdateOne) SetType(v notification.Type) *NotificationUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *NotificationUpdateOne) SetNillableType(v *notification.Type) *NotificationUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *NotificationUpdateOne) SetTitle(v string) *NotificationUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *NotificationUpdateOne) SetNillableTitle(v *string) *NotificationUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *NotificationUpdateOne) SetContent(v string) *NotificationUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *NotificationUpdateOne) SetNillableContent(v *string) *NotificationUpdateOne {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetActorID sets the "actor_id" field.
func (_u *NotificationUpdateOne) SetActorID(v uint64) *NotificationUpdateOne {
	_u.mutation.ResetActorID()
	_u.mutation.SetActorID(v)
	return _u
}

// SetNillableActorID sets the "actor_id" field if the given value is not nil.
func (_u *NotificationUpdateOne) SetNillableActorID(v *uint64) *NotificationUpdateOne {
	if v != nil {
		_u.SetActorID(*v)
	}
	return _u
}

// AddActorID adds value to the "actor_id" field.
func (_u *NotificationUpdateOne) AddActorID(v int64) *NotificationUpdateOne {
	_u.mutation.AddActorID(v)
	return _u
}

// ClearActorID clears the value of the "actor_id" field.
func (_u *NotificationUpdateOne) ClearActorID() *NotificationUpdateOne {
	_u.mutation.ClearActorID()
	return _u
}

// SetTargetID sets the "target_id" field.
func (_u *NotificationUpdateOne) SetTargetID(v uint64) *NotificationUpdateOne {
	_u.mutation.ResetTargetID()
	_u.mutation.SetTargetID(v)
	return _u
}

// SetNillableTargetID sets the "target_id" field if the given value is not nil.
func (_u *NotificationUpdateOne) SetNillableTargetID(v *uint64) *NotificationUpdateOne {
	if v != nil {
		_u.SetTargetID(*v)
	}
	return _u
}

// AddTargetID adds value to the "target_id" field.
func (_u *NotificationUpdateOne) AddTargetID(v int64) *NotificationUpdateOne {
	_u.mutation.AddTargetID(v)
	return _u
}

// ClearTargetID clears the value of the "target_id" field.
func (_u *NotificationUpdateOne) ClearTargetID() *NotificationUpdateOne {
	_u.mutation.ClearTargetID()
	return _u
}

// SetTargetType sets the "target_type" field.
func (_u *NotificationUpdateOne) SetTargetType(v string) *NotificationUpdateOne {
	_u.mutation.SetTargetType(v)
	return _u
}

// SetNillableTargetType sets the "target_type" field if the given value is not nil.
func (_u *NotificationUpdateOne) SetNillableTargetType(v *string) *NotificationUpdateOne {
	if v != nil {
		_u.SetTargetType(*v)
	}
	return _u
}

// ClearTargetType clears the value of the "target_type" field.
func (_u *NotificationUpdateOne) ClearTargetType() *NotificationUpdateOne {
	_u.mutation.ClearTargetType()
	return _u
}

// SetIsRead sets the "is_read" field.
func (_u *NotificationUpdateOne) SetIsRead(v bool) *NotificationUpdateOne {
	_u.mutation.SetIsRead(v)
	return _u
}

// SetNillableIsRead sets the "is_read" field if the given value is not nil.
func (_u *NotificationUpdateOne) SetNillableIsRead(v *bool) *NotificationUpdateOne {
	if v != nil {
		_u.SetIsRead(*v)
	}
	return _u
}

// SetReadAt sets the "read_at" field.
func (_u *NotificationUpdateOne) SetReadAt(v time.Time) *NotificationUpdateOne {
	_u.mutation.SetReadAt(v)
	return _u
}

// SetNillableReadAt sets the "read_at" field if the given value is not nil.
func (_u *NotificationUpdateOne) SetNillableReadAt(v *time.Time) *NotificationUpdateOne {
	if v != nil {
		_u.SetReadAt(*v)
	}
	return _u
}

// ClearReadAt clears the value of the "read_at" field.
func (_u *NotificationUpdateOne) ClearReadAt() *NotificationUpdateOne {
	_u.mutation.ClearReadAt()
	return _u
}

// Mutation returns the NotificationMutation object of the builder.
func (_u *NotificationUpdateOne) Mutation() *NotificationMutation {
	return _u.mutation
}

// Where appends a list predicates to the NotificationUpdate builder.
func (_u *NotificationUpdateOne) Where(ps ...predicate.Notification) *NotificationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *NotificationUpdateOne) Select(field string, fields ...string) *NotificationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Notification entity.
func (_u *NotificationUpdateOne) Save(ctx context.Context) (*Notification, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NotificationUpdateOne) SaveX(ctx context.Context) *Notification {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *NotificationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NotificationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *NotificationUpdateOne) check() error {
	if v, ok := _u.mutation.GetType(); ok {
		if err := notification.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Notification.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Title(); ok {
		if err := notification.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Notification.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TargetType(); ok {
		if err := notification.TargetTypeValidator(v); err != nil {
			return &ValidationError{Name: "target_type", err: fmt.Errorf(`ent: validator failed for field "Notification.target_type": %w`, err)}
		}
	}
	return nil
}

func (_u *NotificationUpdateOne) sqlSave(ctx context.Context) (_node *Notification, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(notification.Table, notification.Columns, sqlgraph.NewFieldSpec(notification.FieldID, field.TypeUint64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Notification.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, notification.FieldID)
		for _, f := range fields {
			if !notification.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != notification.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(notification.FieldUserID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(notification.FieldUserID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(notification.FieldType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(notification.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(notification.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.ActorID(); ok {
		_spec.SetField(notification.FieldActorID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedActorID(); ok {
		_spec.AddField(notification.FieldActorID, field.TypeUint64, value)
	}
	if _u.mutation.ActorIDCleared() {
		_spec.ClearField(notification.FieldActorID, field.TypeUint64)
	}
	if value, ok := _u.mutation.TargetID(); ok {
		_spec.SetField(notification.FieldTargetID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedTargetID(); ok {
		_spec.AddField(notification.FieldTargetID, field.TypeUint64, value)
	}
	if _u.mutation.TargetIDCleared() {
		_spec.ClearField(notification.FieldTargetID, field.TypeUint64)
	}
	if value, ok := _u.mutation.TargetType(); ok {
		_spec.SetField(notification.FieldTargetType, field.TypeString, value)
	}
	if _u.mutation.TargetTypeCleared() {
		_spec.ClearField(notification.FieldTargetType, field.TypeString)
	}
	if value, ok := _u.mutation.IsRead(); ok {
		_spec.SetField(notification.FieldIsRead, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ReadAt(); ok {
		_spec.SetField(notification.FieldReadAt, field.TypeTime, value)
	}
	if _u.mutation.ReadAtCleared() {
		_spec.ClearField(notification.FieldReadAt, field.TypeTime)
	}
	_node = &Notification{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{notification.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
