// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/blog/blog-community/internal/ent/post"
)

// PostCreate is the builder for creating a Post entity.
type PostCreate struct {
	config
	mutation *PostMutation
	hooks    []Hook
}

// SetTitle sets the "title" field.
func (_c *PostCreate) SetTitle(v string) *PostCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetContent sets the "content" field.
func (_c *PostCreate) SetContent(v string) *PostCreate {
	_c.mutation.SetContent(v)
	return _c
}

// SetSummary sets the "summary" field.
func (_c *PostCreate) SetSummary(v string) *PostCreate {
	_c.mutation.SetSummary(v)
	return _c
}

// SetNillableSummary sets the "summary" field if the given value is not nil.
func (_c *PostCreate) SetNillableSummary(v *string) *PostCreate {
	if v != nil {
		_c.SetSummary(*v)
	}
	return _c
}

// SetContentType sets the "content_type" field.
func (_c *PostCreate) SetContentType(v post.ContentType) *PostCreate {
	_c.mutation.SetContentType(v)
	return _c
}

// SetNillableContentType sets the "content_type" field if the given value is not nil.
func (_c *PostCreate) SetNillableContentType(v *post.ContentType) *PostCreate {
	if v != nil {
		_c.SetContentType(*v)
	}
	return _c
}

// SetCoverImage sets the "cover_image" field.
func (_c *PostCreate) SetCoverImage(v string) *PostCreate {
	_c.mutation.SetCoverImage(v)
	return _c
}

// SetNillableCoverImage sets the "cover_image" field if the given value is not nil.
func (_c *PostCreate) SetNillableCoverImage(v *string) *PostCreate {
	if v != nil {
		_c.SetCoverImage(*v)
	}
	return _c
}

// SetAuthorID sets the "author_id" field.
func (_c *PostCreate) SetAuthorID(v uint64) *PostCreate {
	_c.mutation.SetAuthorID(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *PostCreate) SetStatus(v post.Status) *PostCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *PostCreate) SetNillableStatus(v *post.Status) *PostCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetViewCount sets the "view_count" field.
func (_c *PostCreate) SetViewCount(v int) *PostCreate {
	_c.mutation.SetViewCount(v)
	return _c
}

// SetNillableViewCount sets the "view_count" field if the given value is not nil.
func (_c *PostCreate) SetNillableViewCount(v *int) *PostCreate {
	if v != nil {
		_c.SetViewCount(*v)
	}
	return _c
}

// SetLikeCount sets the "like_count" field.
func (_c *PostCreate) SetLikeCount(v int) *PostCreate {
	_c.mutation.SetLikeCount(v)
	return _c
}

// SetNillableLikeCount sets the "like_count" field if the given value is not nil.
func (_c *PostCreate) SetNillableLikeCount(v *int) *PostCreate {
	if v != nil {
		_c.SetLikeCount(*v)
	}
	return _c
}

// SetCommentCount sets the "comment_count" field.
func (_c *PostCreate) SetCommentCount(v int) *PostCreate {
	_c.mutation.SetCommentCount(v)
	return _c
}

// SetNillableCommentCount sets the "comment_count" field if the given value is not nil.
func (_c *PostCreate) SetNillableCommentCount(v *int) *PostCreate {
	if v != nil {
		_c.SetCommentCount(*v)
	}
	return _c
}

// SetCollectCount sets the "collect_count" field.
func (_c *PostCreate) SetCollectCount(v int) *PostCreate {
	_c.mutation.SetCollectCount(v)
	return _c
}

// SetNillableCollectCount sets the "collect_count" field if the given value is not nil.
func (_c *PostCreate) SetNillableCollectCount(v *int) *PostCreate {
	if v != nil {
		_c.SetCollectCount(*v)
	}
	return _c
}

// SetTags sets the "tags" field.
func (_c *PostCreate) SetTags(v []string) *PostCreate {
	_c.mutation.SetTags(v)
	return _c
}

// SetPublishedAt sets the "published_at" field.
func (_c *PostCreate) SetPublishedAt(v time.Time) *PostCreate {
	_c.mutation.SetPublishedAt(v)
	return _c
}

// SetNillablePublishedAt sets the "published_at" field if the given value is not nil.
func (_c *PostCreate) SetNillablePublishedAt(v *time.Time) *PostCreate {
	if v != nil {
		_c.SetPublishedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *PostCreate) SetCreatedAt(v time.Time) *PostCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PostCreate) SetNillableCreatedAt(v *time.Time) *PostCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *PostCreate) SetUpdatedAt(v time.Time) *PostCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *PostCreate) SetNillableUpdatedAt(v *time.Time) *PostCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *PostCreate) SetID(v uint64) *PostCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the PostMutation object of the builder.
func (_c *PostCreate) Mutation() *PostMutation {
	return _c.mutation
}

// Save creates the Post in the database.
func (_c *PostCreate) Save(ctx context.Context) (*Post, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PostCreate) SaveX(ctx context.Context) *Post {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PostCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PostCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PostCreate) defaults() {
	if _, ok := _c.mutation.ContentType(); !ok {
		v := post.DefaultContentType
		_c.mutation.SetContentType(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := post.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.ViewCount(); !ok {
		v := post.DefaultViewCount
		_c.mutation.SetViewCount(v)
	}
	if _, ok := _c.mutation.LikeCount(); !ok {
		v := post.DefaultLikeCount
		_c.mutation.SetLikeCount(v)
	}
	if _, ok := _c.mutation.CommentCount(); !ok {
		v := post.DefaultCommentCount
		_c.mutation.SetCommentCount(v)
	}
	if _, ok := _c.mutation.CollectCount(); !ok {
		v := post.DefaultCollectCount
		_c.mutation.SetCollectCount(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := post.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := post.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PostCreate) check() error {
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Post.title"`)}
	}
	if v, ok := _c.mutation.Title(); ok {
		if err := post.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Post.title": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Content(); !ok {
		return &ValidationError{Name: "content", err: errors.New(`ent: missing required field "Post.content"`)}
	}
	if v, ok := _c.mutation.Summary(); ok {
		if err := post.SummaryValidator(v); err != nil {
			return &ValidationError{Name: "summary", err: fmt.Errorf(`ent: validator failed for field "Post.summary": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ContentType(); !ok {
		return &ValidationError{Name: "content_type", err: errors.New(`ent: missing required field "Post.content_type"`)}
	}
	if v, ok := _c.mutation.ContentType(); ok {
		if err := post.ContentTypeValidator(v); err != nil {
			return &ValidationError{Name: "content_type", err: fmt.Errorf(`ent: validator failed for field "Post.content_type": %w`, err)}
		}
	}
	if v, ok := _c.mutation.CoverImage(); ok {
		if err := post.CoverImageValidator(v); err != nil {
			return &ValidationError{Name: "cover_image", err: fmt.Errorf(`ent: validator failed for field "Post.cover_image": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AuthorID(); !ok {
		return &ValidationError{Name: "author_id", err: errors.New(`ent: missing required field "Post.author_id"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Post.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := post.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Post.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ViewCount(); !ok {
		return &ValidationError{Name: "view_count", err: errors.New(`ent: missing required field "Post.view_count"`)}
	}
	if _, ok := _c.mutation.LikeCount(); !ok {
		return &ValidationError{Name: "like_count", err: errors.New(`ent: missing required field "Post.like_count"`)}
	}
	if _, ok := _c.mutation.CommentCount(); !ok {
		return &ValidationError{Name: "comment_count", err: errors.New(`ent: missing required field "Post.comment_count"`)}
	}
	if _, ok := _c.mutation.CollectCount(); !ok {
		return &ValidationError{Name: "collect_count", err: errors.New(`ent: missing required field "Post.collect_count"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Post.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Post.updated_at"`)}
	}
	return nil
}

func (_c *PostCreate) sqlSave(ctx context.Context) (*Post, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PostCreate) createSpec() (*Post, *sqlgraph.CreateSpec) {
	var (
		_node = &Post{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(post.Table, sqlgraph.NewFieldSpec(post.FieldID, field.TypeUint64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(post.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Content(); ok {
		_spec.SetField(post.FieldContent, field.TypeString, value)
		_node.Content = value
	}
	if value, ok := _c.mutation.Summary(); ok {
		_spec.SetField(post.FieldSummary, field.TypeString, value)
		_node.Summary = value
	}
	if value, ok := _c.mutation.ContentType(); ok {
		_spec.SetField(post.FieldContentType, field.TypeEnum, value)
		_node.ContentType = value
	}
	if value, ok := _c.mutation.CoverImage(); ok {
		_spec.SetField(post.FieldCoverImage, field.TypeString, value)
		_node.CoverImage = value
	}
	if value, ok := _c.mutation.AuthorID(); ok {
		_spec.SetField(post.FieldAuthorID, field.TypeUint64, value)
		_node.AuthorID = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(post.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.ViewCount(); ok {
		_spec.SetField(post.FieldViewCount, field.TypeInt, value)
		_node.ViewCount = value
	}
	if value, ok := _c.mutation.LikeCount(); ok {
		_spec.SetField(post.FieldLikeCount, field.TypeInt, value)
		_node.LikeCount = value
	}
	if value, ok := _c.mutation.CommentCount(); ok {
		_spec.SetField(post.FieldCommentCount, field.TypeInt, value)
		_node.CommentCount = value
	}
	if value, ok := _c.mutation.CollectCount(); ok {
		_spec.SetField(post.FieldCollectCount, field.TypeInt, value)
		_node.CollectCount = value
	}
	if value, ok := _c.mutation.Tags(); ok {
		_spec.SetField(post.FieldTags, field.TypeJSON, value)
		_node.Tags = value
	}
	if value, ok := _c.mutation.PublishedAt(); ok {
		_spec.SetField(post.FieldPublishedAt, field.TypeTime, value)
		_node.PublishedAt = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(post.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(post.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// PostCreateBulk is the builder for creating many Post entities in bulk.
type PostCreateBulk struct {
	config
	err      error
	builders []*PostCreate
}

// Save creates the Post entities in the database.
func (_c *PostCreateBulk) Save(ctx context.Context) ([]*Post, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Post, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PostMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PostCreateBulk) SaveX(ctx context.Context) []*Post {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PostCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PostCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
