// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/blog/blog-community/internal/ent/post"
	"github.com/blog/blog-community/internal/ent/predicate"
)

// PostUpdate is the builder for updating Post entities.
type PostUpdate struct {
	config
	hooks    []Hook
	mutation *PostMutation
}

// Where appends a list predicates to the PostUpdate builder.
func (_u *PostUpdate) Where(ps ...predicate.Post) *PostUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTitle sets the "title" field.
func (_u *PostUpdate) SetTitle(v string) *PostUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *PostUpdate) SetNillableTitle(v *string) *PostUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *PostUpdate) SetContent(v string) *PostUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *PostUpdate) SetNillableContent(v *string) *PostUpdate {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetSummary sets the "summary" field.
func (_u *PostUpdate) SetSummary(v string) *PostUpdate {
	_u.mutation.SetSummary(v)
	return _u
}

// SetNillableSummary sets the "summary" field if the given value is not nil.
func (_u *PostUpdate) SetNillableSummary(v *string) *PostUpdate {
	if v != nil {
		_u.SetSummary(*v)
	}
	return _u
}

// ClearSummary clears the value of the "summary" field.
func (_u *PostUpdate) ClearSummary() *PostUpdate {
	_u.mutation.ClearSummary()
	return _u
}

// SetContentType sets the "content_type" field.
func (_u *PostUpdate) SetContentType(v post.ContentType) *PostUpdate {
	_u.mutation.SetContentType(v)
	return _u
}

// SetNillableContentType sets the "content_type" field if the given value is not nil.
func (_u *PostUpdate) SetNillableContentType(v *post.ContentType) *PostUpdate {
	if v != nil {
		_u.SetContentType(*v)
	}
	return _u
}

// SetCoverImage sets the "cover_image" field.
func (_u *PostUpdate) SetCoverImage(v string) *PostUpdate {
	_u.mutation.SetCoverImage(v)
	return _u
}

// SetNillableCoverImage sets the "cover_image" field if the given value is not nil.
func (_u *PostUpdate) SetNillableCoverImage(v *string) *PostUpdate {
	if v != nil {
		_u.SetCoverImage(*v)
	}
	return _u
}

// ClearCoverImage clears the value of the "cover_image" field.
func (_u *PostUpdate) ClearCoverImage() *PostUpdate {
	_u.mutation.ClearCoverImage()
	return _u
}

// SetAuthorID sets the "author_id" field.
func (_u *PostUpdate) SetAuthorID(v uint64) *PostUpdate {
	_u.mutation.ResetAuthorID()
	_u.mutation.SetAuthorID(v)
	return _u
}

// SetNillableAuthorID sets the "author_id" field if the given value is not nil.
func (_u *PostUpdate) SetNillableAuthorID(v *uint64) *PostUpdate {
	if v != nil {
		_u.SetAuthorID(*v)
	}
	return _u
}

// AddAuthorID adds value to the "author_id" field.
func (_u *PostUpdate) AddAuthorID(v int64) *PostUpdate {
	_u.mutation.AddAuthorID(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *PostUpdate) SetStatus(v post.Status) *PostUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PostUpdate) SetNillableStatus(v *post.Status) *PostUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetViewCount sets the "view_count" field.
func (_u *PostUpdate) SetViewCount(v int) *PostUpdate {
	_u.mutation.ResetViewCount()
	_u.mutation.SetViewCount(v)
	return _u
}

// SetNillableViewCount sets the "view_count" field if the given value is not nil.
func (_u *PostUpdate) SetNillableViewCount(v *int) *PostUpdate {
	if v != nil {
		_u.SetViewCount(*v)
	}
	return _u
}

// AddViewCount adds value to the "view_count" field.
func (_u *PostUpdate) AddViewCount(v int) *PostUpdate {
	_u.mutation.AddViewCount(v)
	return _u
}

// SetLikeCount sets the "like_count" field.
func (_u *PostUpdate) SetLikeCount(v int) *PostUpdate {
	_u.mutation.ResetLikeCount()
	_u.mutation.SetLikeCount(v)
	return _u
}

// SetNillableLikeCount sets the "like_count" field if the given value is not nil.
func (_u *PostUpdate) SetNillableLikeCount(v *int) *PostUpdate {
	if v != nil {
		_u.SetLikeCount(*v)
	}
	return _u
}

// AddLikeCount adds value to the "like_count" field.
func (_u *PostUpdate) AddLikeCount(v int) *PostUpdate {
	_u.mutation.AddLikeCount(v)
	return _u
}

// SetCommentCount sets the "comment_count" field.
func (_u *PostUpdate) SetCommentCount(v int) *PostUpdate {
	_u.mutation.ResetCommentCount()
	_u.mutation.SetCommentCount(v)
	return _u
}

// SetNillableCommentCount sets the "comment_count" field if the given value is not nil.
func (_u *PostUpdate) SetNillableCommentCount(v *int) *PostUpdate {
	if v != nil {
		_u.SetCommentCount(*v)
	}
	return _u
}

// AddCommentCount adds value to the "comment_count" field.
func (_u *PostUpdate) AddCommentCount(v int) *PostUpdate {
	_u.mutation.AddCommentCount(v)
	return _u
}

// SetCollectCount sets the "collect_count" field.
func (_u *PostUpdate) SetCollectCount(v int) *PostUpdate {
	_u.mutation.ResetCollectCount()
	_u.mutation.SetCollectCount(v)
	return _u
}

// SetNillableCollectCount sets the "collect_count" field if the given value is not nil.
func (_u *PostUpdate) SetNillableCollectCount(v *int) *PostUpdate {
	if v != nil {
		_u.SetCollectCount(*v)
	}
	return _u
}

// AddCollectCount adds value to the "collect_count" field.
func (_u *PostUpdate) AddCollectCount(v int) *PostUpdate {
	_u.mutation.AddCollectCount(v)
	return _u
}

// SetTags sets the "tags" field.
func (_u *PostUpdate) SetTags(v []string) *PostUpdate {
	_u.mutation.SetTags(v)
	return _u
}

// AppendTags appends value to the "tags" field.
func (_u *PostUpdate) AppendTags(v []string) *PostUpdate {
	_u.mutation.AppendTags(v)
	return _u
}

// ClearTags clears the value of the "tags" field.
func (_u *PostUpdate) ClearTags() *PostUpdate {
	_u.mutation.ClearTags()
	return _u
}

// SetPublishedAt sets the "published_at" field.
func (_u *PostUpdate) SetPublishedAt(v time.Time) *PostUpdate {
	_u.mutation.SetPublishedAt(v)
	return _u
}

// SetNillablePublishedAt sets the "published_at" field if the given value is not nil.
func (_u *PostUpdate) SetNillablePublishedAt(v *time.Time) *PostUpdate {
	if v != nil {
		_u.SetPublishedAt(*v)
	}
	return _u
}

// ClearPublishedAt clears the value of the "published_at" field.
func (_u *PostUpdate) ClearPublishedAt() *PostUpdate {
	_u.mutation.ClearPublishedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PostUpdate) SetUpdatedAt(v time.Time) *PostUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the PostMutation object of the builder.
func (_u *PostUpdate) Mutation() *PostMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PostUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PostUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PostUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PostUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PostUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := post.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PostUpdate) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := post.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Post.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Summary(); ok {
		if err := post.SummaryValidator(v); err != nil {
			return &ValidationError{Name: "summary", err: fmt.Errorf(`ent: validator failed for field "Post.summary": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ContentType(); ok {
		if err := post.ContentTypeValidator(v); err != nil {
			return &ValidationError{Name: "content_type", err: fmt.Errorf(`ent: validator failed for field "Post.content_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CoverImage(); ok {
		if err := post.CoverImageValidator(v); err != nil {
			return &ValidationError{Name: "cover_image", err: fmt.Errorf(`ent: validator failed for field "Post.cover_image": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := post.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Post.status": %w`, err)}
		}
	}
	return nil
}

func (_u *PostUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(post.Table, post.Columns, sqlgraph.NewFieldSpec(post.FieldID, field.TypeUint64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(post.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(post.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.Summary(); ok {
		_spec.SetField(post.FieldSummary, field.TypeString, value)
	}
	if _u.mutation.SummaryCleared() {
		_spec.ClearField(post.FieldSummary, field.TypeString)
	}
	if value, ok := _u.mutation.ContentType(); ok {
		_spec.SetField(post.FieldContentType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.CoverImage(); ok {
		_spec.SetField(post.FieldCoverImage, field.TypeString, value)
	}
	if _u.mutation.CoverImageCleared() {
		_spec.ClearField(post.FieldCoverImage, field.TypeString)
	}
	if value, ok := _u.mutation.AuthorID(); ok {
		_spec.SetField(post.FieldAuthorID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedAuthorID(); ok {
		_spec.AddField(post.FieldAuthorID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(post.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ViewCount(); ok {
		_spec.SetField(post.FieldViewCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedViewCount(); ok {
		_spec.AddField(post.FieldViewCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LikeCount(); ok {
		_spec.SetField(post.FieldLikeCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLikeCount(); ok {
		_spec.AddField(post.FieldLikeCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CommentCount(); ok {
		_spec.SetField(post.FieldCommentCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCommentCount(); ok {
		_spec.AddField(post.FieldCommentCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CollectCount(); ok {
		_spec.SetField(post.FieldCollectCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCollectCount(); ok {
		_spec.AddField(post.FieldCollectCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Tags(); ok {
		_spec.SetField(post.FieldTags, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, post.FieldTags, value)
		})
	}
	if _u.mutation.TagsCleared() {
		_spec.ClearField(post.FieldTags, field.TypeJSON)
	}
	if value, ok := _u.mutation.PublishedAt(); ok {
		_spec.SetField(post.FieldPublishedAt, field.TypeTime, value)
	}
	if _u.mutation.PublishedAtCleared() {
		_spec.ClearField(post.FieldPublishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(post.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{post.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PostUpdateOne is the builder for updating a single Post entity.
type PostUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PostMutation
}

// SetTitle sets the "title" field.
func (_u *PostUpdateOne) SetTitle(v string) *PostUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *PostUpdateOne) SetNillableTitle(v *string) *PostUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *PostUpdateOne) SetContent(v string) *PostUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *PostUpdateOne) SetNillableContent(v *string) *PostUpdateOne {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetSummary sets the "summary" field.
func (_u *PostUpdateOne) SetSummary(v string) *PostUpdateOne {
	_u.mutation.SetSummary(v)
	return _u
}

// SetNillableSummary sets the "summary" field if the given value is not nil.
func (_u *PostUpdateOne) SetNillableSummary(v *string) *PostUpdateOne {
	if v != nil {
		_u.SetSummary(*v)
	}
	return _u
}

// ClearSummary clears the value of the "summary" field.
func (_u *PostUpdateOne) ClearSummary() *PostUpdateOne {
	_u.mutation.ClearSummary()
	return _u
}

// SetContentType sets the "content_type" field.
func (_u *PostUpdateOne) SetContentType(v post.ContentType) *PostUpdateOne {
	_u.mutation.SetContentType(v)
	return _u
}

// SetNillableContentType sets the "content_type" field if the given value is not nil.
func (_u *PostUpdateOne) SetNillableContentType(v *post.ContentType) *PostUpdateOne {
	if v != nil {
		_u.SetContentType(*v)
	}
	return _u
}

// SetCoverImage sets the "cover_image" field.
func (_u *PostUpdateOne) SetCoverImage(v string) *PostUpdateOne {
	_u.mutation.SetCoverImage(v)
	return _u
}

// SetNillableCoverImage sets the "cover_image" field if the given value is not nil.
func (_u *PostUpdateOne) SetNillableCoverImage(v *string) *PostUpdateOne {
	if v != nil {
		_u.SetCoverImage(*v)
	}
	return _u
}

// ClearCoverImage clears the value of the "cover_image" field.
func (_u *PostUpdateOne) ClearCoverImage() *PostUpdateOne {
	_u.mutation.ClearCoverImage()
	return _u
}

// SetAuthorID sets the "author_id" field.
func (_u *PostUpdateOne) SetAuthorID(v uint64) *PostUpdateOne {
	_u.mutation.ResetAuthorID()
	_u.mutation.SetAuthorID(v)
	return _u
}

// SetNillableAuthorID sets the "author_id" field if the given value is not nil.
func (_u *PostUpdateOne) SetNillableAuthorID(v *uint64) *PostUpdateOne {
	if v != nil {
		_u.SetAuthorID(*v)
	}
	return _u
}

// AddAuthorID adds value to the "author_id" field.
func (_u *PostUpdateOne) AddAuthorID(v int64) *PostUpdateOne {
	_u.mutation.AddAuthorID(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *PostUpdateOne) SetStatus(v post.Status) *PostUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PostUpdateOne) SetNillableStatus(v *post.Status) *PostUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetViewCount sets the "view_count" field.
func (_u *PostUpdateOne) SetViewCount(v int) *PostUpdateOne {
	_u.mutation.ResetViewCount()
	_u.mutation.SetViewCount(v)
	return _u
}

// SetNillableViewCount sets the "view_count" field if the given value is not nil.
func (_u *PostUpdateOne) SetNillableViewCount(v *int) *PostUpdateOne {
	if v != nil {
		_u.SetViewCount(*v)
	}
	return _u
}

// AddViewCount adds value to the "view_count" field.
func (_u *PostUpdateOne) AddViewCount(v int) *PostUpdateOne {
	_u.mutation.AddViewCount(v)
	return _u
}

// SetLikeCount sets the "like_count" field.
func (_u *PostUpdateOne) SetLikeCount(v int) *PostUpdateOne {
	_u.mutation.ResetLikeCount()
	_u.mutation.SetLikeCount(v)
	return _u
}

// SetNillableLikeCount sets the "like_count" field if the given value is not nil.
func (_u *PostUpdateOne) SetNillableLikeCount(v *int) *PostUpdateOne {
	if v != nil {
		_u.SetLikeCount(*v)
	}
	return _u
}

// AddLikeCount adds value to the "like_count" field.
func (_u *PostUpdateOne) AddLikeCount(v int) *PostUpdateOne {
	_u.mutation.AddLikeCount(v)
	return _u
}

// SetCommentCount sets the "comment_count" field.
func (_u *PostUpdateOne) SetCommentCount(v int) *PostUpdateOne {
	_u.mutation.ResetCommentCount()
	_u.mutation.SetCommentCount(v)
	return _u
}

// SetNillableCommentCount sets the "comment_count" field if the given value is not nil.
func (_u *PostUpdateOne) SetNillableCommentCount(v *int) *PostUpdateOne {
	if v != nil {
		_u.SetCommentCount(*v)
	}
	return _u
}

// AddCommentCount adds value to the "comment_count" field.
func (_u *PostUpdateOne) AddCommentCount(v int) *PostUpdateOne {
	_u.mutation.AddCommentCount(v)
	return _u
}

// SetCollectCount sets the "collect_count" field.
func (_u *PostUpdateOne) SetCollectCount(v int) *PostUpdateOne {
	_u.mutation.ResetCollectCount()
	_u.mutation.SetCollectCount(v)
	return _u
}

// SetNillableCollectCount sets the "collect_count" field if the given value is not nil.
func (_u *PostUpdateOne) SetNillableCollectCount(v *int) *PostUpdateOne {
	if v != nil {
		_u.SetCollectCount(*v)
	}
	return _u
}

// AddCollectCount adds value to the "collect_count" field.
func (_u *PostUpdateOne) AddCollectCount(v int) *PostUpdateOne {
	_u.mutation.AddCollectCount(v)
	return _u
}

// SetTags sets the "tags" field.
func (_u *PostUpdateOne) SetTags(v []string) *PostUpdateOne {
	_u.mutation.SetTags(v)
	return _u
}

// AppendTags appends value to the "tags" field.
func (_u *PostUpdateOne) AppendTags(v []string) *PostUpdateOne {
	_u.mutation.AppendTags(v)
	return _u
}

// ClearTags clears the value of the "tags" field.
func (_u *PostUpdateOne) ClearTags() *PostUpdateOne {
	_u.mutation.ClearTags()
	return _u
}

// SetPublishedAt sets the "published_at" field.
func (_u *PostUpdateOne) SetPublishedAt(v time.Time) *PostUpdateOne {
	_u.mutation.SetPublishedAt(v)
	return _u
}

// SetNillablePublishedAt sets the "published_at" field if the given value is not nil.
func (_u *PostUpdateOne) SetNillablePublishedAt(v *time.Time) *PostUpdateOne {
	if v != nil {
		_u.SetPublishedAt(*v)
	}
	return _u
}

// ClearPublishedAt clears the value of the "published_at" field.
func (_u *PostUpdateOne) ClearPublishedAt() *PostUpdateOne {
	_u.mutation.ClearPublishedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PostUpdateOne) SetUpdatedAt(v time.Time) *PostUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the PostMutation object of the builder.
func (_u *PostUpdateOne) Mutation() *PostMutation {
	return _u.mutation
}

// Where appends a list predicates to the PostUpdate builder.
func (_u *PostUpdateOne) Where(ps ...predicate.Post) *PostUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PostUpdateOne) Select(field string, fields ...string) *PostUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Post entity.
func (_u *PostUpdateOne) Save(ctx context.Context) (*Post, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PostUpdateOne) SaveX(ctx context.Context) *Post {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PostUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PostUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PostUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := post.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PostUpdateOne) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := post.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Post.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Summary(); ok {
		if err := post.SummaryValidator(v); err != nil {
			return &ValidationError{Name: "summary", err: fmt.Errorf(`ent: validator failed for field "Post.summary": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ContentType(); ok {
		if err := post.ContentTypeValidator(v); err != nil {
			return &ValidationError{Name: "content_type", err: fmt.Errorf(`ent: validator failed for field "Post.content_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CoverImage(); ok {
		if err := post.CoverImageValidator(v); err != nil {
			return &ValidationError{Name: "cover_image", err: fmt.Errorf(`ent: validator failed for field "Post.cover_image": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := post.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Post.status": %w`, err)}
		}
	}
	return nil
}

func (_u *PostUpdateOne) sqlSave(ctx context.Context) (_node *Post, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(post.Table, post.Columns, sqlgraph.NewFieldSpec(post.FieldID, field.TypeUint64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Post.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, post.FieldID)
		for _, f := range fields {
			if !post.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != post.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(post.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(post.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.Summary(); ok {
		_spec.SetField(post.FieldSummary, field.TypeString, value)
	}
	if _u.mutation.SummaryCleared() {
		_spec.ClearField(post.FieldSummary, field.TypeString)
	}
	if value, ok := _u.mutation.ContentType(); ok {
		_spec.SetField(post.FieldContentType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.CoverImage(); ok {
		_spec.SetField(post.FieldCoverImage, field.TypeString, value)
	}
	if _u.mutation.CoverImageCleared() {
		_spec.ClearField(post.FieldCoverImage, field.TypeString)
	}
	if value, ok := _u.mutation.AuthorID(); ok {
		_spec.SetField(post.FieldAuthorID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedAuthorID(); ok {
		_spec.AddField(post.FieldAuthorID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(post.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ViewCount(); ok {
		_spec.SetField(post.FieldViewCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedViewCount(); ok {
		_spec.AddField(post.FieldViewCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LikeCount(); ok {
		_spec.SetField(post.FieldLikeCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLikeCount(); ok {
		_spec.AddField(post.FieldLikeCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CommentCount(); ok {
		_spec.SetField(post.FieldCommentCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCommentCount(); ok {
		_spec.AddField(post.FieldCommentCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CollectCount(); ok {
		_spec.SetField(post.FieldCollectCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCollectCount(); ok {
		_spec.AddField(post.FieldCollectCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Tags(); ok {
		_spec.SetField(post.FieldTags, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, post.FieldTags, value)
		})
	}
	if _u.mutation.TagsCleared() {
		_spec.ClearField(post.FieldTags, field.TypeJSON)
	}
	if value, ok := _u.mutation.PublishedAt(); ok {
		_spec.SetField(post.FieldPublishedAt, field.TypeTime, value)
	}
	if _u.mutation.PublishedAtCleared() {
		_spec.ClearField(post.FieldPublishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(post.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &Post{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{post.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
