// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/blog/blog-community/internal/ent/collectrecord"
	"github.com/blog/blog-community/internal/ent/comment"
	"github.com/blog/blog-community/internal/ent/follow"
	"github.com/blog/blog-community/internal/ent/likerecord"
	"github.com/blog/blog-community/internal/ent/post"
	"github.com/blog/blog-community/internal/ent/schema"
	"github.com/blog/blog-community/internal/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	collectrecordFields := schema.CollectRecord{}.Fields()
	_ = collectrecordFields
	// collectrecordDescCreatedAt is the schema descriptor for created_at field.
	collectrecordDescCreatedAt := collectrecordFields[4].Descriptor()
	// collectrecord.DefaultCreatedAt holds the default value on creation for the created_at field.
	collectrecord.DefaultCreatedAt = collectrecordDescCreatedAt.Default.(func() time.Time)
	commentFields := schema.Comment{}.Fields()
	_ = commentFields
	// commentDescLikeCount is the schema descriptor for like_count field.
	commentDescLikeCount := commentFields[5].Descriptor()
	// comment.DefaultLikeCount holds the default value on creation for the like_count field.
	comment.DefaultLikeCount = commentDescLikeCount.Default.(int)
	// commentDescCreatedAt is the schema descriptor for created_at field.
	commentDescCreatedAt := commentFields[6].Descriptor()
	// comment.DefaultCreatedAt holds the default value on creation for the created_at field.
	comment.DefaultCreatedAt = commentDescCreatedAt.Default.(func() time.Time)
	// commentDescUpdatedAt is the schema descriptor for updated_at field.
	commentDescUpdatedAt := commentFields[7].Descriptor()
	// comment.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	comment.DefaultUpdatedAt = commentDescUpdatedAt.Default.(func() time.Time)
	// comment.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	comment.UpdateDefaultUpdatedAt = commentDescUpdatedAt.UpdateDefault.(func() time.Time)
	followFields := schema.Follow{}.Fields()
	_ = followFields
	// followDescCreatedAt is the schema descriptor for created_at field.
	followDescCreatedAt := followFields[3].Descriptor()
	// follow.DefaultCreatedAt holds the default value on creation for the created_at field.
	follow.DefaultCreatedAt = followDescCreatedAt.Default.(func() time.Time)
	likerecordFields := schema.LikeRecord{}.Fields()
	_ = likerecordFields
	// likerecordDescCreatedAt is the schema descriptor for created_at field.
	likerecordDescCreatedAt := likerecordFields[4].Descriptor()
	// likerecord.DefaultCreatedAt holds the default value on creation for the created_at field.
	likerecord.DefaultCreatedAt = likerecordDescCreatedAt.Default.(func() time.Time)
	postFields := schema.Post{}.Fields()
	_ = postFields
	// postDescTitle is the schema descriptor for title field.
	postDescTitle := postFields[1].Descriptor()
	// post.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	post.TitleValidator = postDescTitle.Validators[0].(func(string) error)
	// postDescSummary is the schema descriptor for summary field.
	postDescSummary := postFields[3].Descriptor()
	// post.SummaryValidator is a validator for the "summary" field. It is called by the builders before save.
	post.SummaryValidator = postDescSummary.Validators[0].(func(string) error)
	// postDescCoverImage is the schema descriptor for cover_image field.
	postDescCoverImage := postFields[5].Descriptor()
	// post.CoverImageValidator is a validator for the "cover_image" field. It is called by the builders before save.
	post.CoverImageValidator = postDescCoverImage.Validators[0].(func(string) error)
	// postDescViewCount is the schema descriptor for view_count field.
	postDescViewCount := postFields[8].Descriptor()
	// post.DefaultViewCount holds the default value on creation for the view_count field.
	post.DefaultViewCount = postDescViewCount.Default.(int)
	// postDescLikeCount is the schema descriptor for like_count field.
	postDescLikeCount := postFields[9].Descriptor()
	// post.DefaultLikeCount holds the default value on creation for the like_count field.
	post.DefaultLikeCount = postDescLikeCount.Default.(int)
	// postDescCommentCount is the schema descriptor for comment_count field.
	postDescCommentCount := postFields[10].Descriptor()
	// post.DefaultCommentCount holds the default value on creation for the comment_count field.
	post.DefaultCommentCount = postDescCommentCount.Default.(int)
	// postDescCollectCount is the schema descriptor for collect_count field.
	postDescCollectCount := postFields[11].Descriptor()
	// post.DefaultCollectCount holds the default value on creation for the collect_count field.
	post.DefaultCollectCount = postDescCollectCount.Default.(int)
	// postDescCreatedAt is the schema descriptor for created_at field.
	postDescCreatedAt := postFields[14].Descriptor()
	// post.DefaultCreatedAt holds the default value on creation for the created_at field.
	post.DefaultCreatedAt = postDescCreatedAt.Default.(func() time.Time)
	// postDescUpdatedAt is the schema descriptor for updated_at field.
	postDescUpdatedAt := postFields[15].Descriptor()
	// post.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	post.DefaultUpdatedAt = postDescUpdatedAt.Default.(func() time.Time)
	// post.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	post.UpdateDefaultUpdatedAt = postDescUpdatedAt.UpdateDefault.(func() time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[1].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = userDescEmail.Validators[0].(func(string) error)
	// userDescUsername is the schema descriptor for username field.
	userDescUsername := userFields[2].Descriptor()
	// user.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	user.UsernameValidator = userDescUsername.Validators[0].(func(string) error)
	// userDescAvatarURL is the schema descriptor for avatar_url field.
	userDescAvatarURL := userFields[4].Descriptor()
	// user.AvatarURLValidator is a validator for the "avatar_url" field. It is called by the builders before save.
	user.AvatarURLValidator = userDescAvatarURL.Validators[0].(func(string) error)
	// userDescRole is the schema descriptor for role field.
	userDescRole := userFields[7].Descriptor()
	// user.DefaultRole holds the default value on creation for the role field.
	user.DefaultRole = userDescRole.Default.(string)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[8].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[9].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
}
