// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package follow

import (
	"github.com/blog/blog-community/internal/ent"
	"github.com/blog/blog-community/internal/follow/application"
	"github.com/blog/blog-community/internal/follow/delivery"
	"github.com/blog/blog-community/internal/follow/infrastructure"
	"github.com/blog/blog-community/internal/notification/domain"
)

// Injectors from wire.go:

// InitializeHandler injects follow dependencies.
func InitializeHandler(client *ent.Client, notifier domain.Notifier) *delivery.FollowHandler {
	repository := infrastructure.NewEntFollowRepo(client)
	useCase := application.NewFollowUseCase(repository, notifier)
	followHandler := delivery.NewFollowHandler(useCase)
	return followHandler
}
