// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint64, Increment: true},
		{Name: "email", Type: field.TypeString, Unique: true, Size: 128},
		{Name: "username", Type: field.TypeString, Unique: true, Size: 64},
		{Name: "password_hash", Type: field.TypeString, Nullable: true},
		{Name: "avatar_url", Type: field.TypeString, Nullable: true, Size: 512},
		{Name: "oauth_provider", Type: field.TypeEnum, Enums: []string{"none", "github", "google"}, Default: "none"},
		{Name: "oauth_id", Type: field.TypeString, Nullable: true},
		{Name: "role", Type: field.TypeString, Default: "user"},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "user_oauth_provider_oauth_id",
				Unique:  true,
				Columns: []*schema.Column{UsersColumns[5], UsersColumns[6]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		UsersTable,
	}
)

func init() {
}
