// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package feed

import (
	"github.com/blog/blog-community/internal/ent"
	application2 "github.com/blog/blog-community/internal/feed/application"
	"github.com/blog/blog-community/internal/feed/delivery"
	infrastructure2 "github.com/blog/blog-community/internal/follow/infrastructure"
	"github.com/blog/blog-community/internal/post/application"
	"github.com/blog/blog-community/internal/post/infrastructure"
	"github.com/redis/go-redis/v9"
)

// Injectors from wire.go:

// InitializeHandler injects feed dependencies.
func InitializeHandler(client *ent.Client, redisClient *redis.Client) *delivery.FeedHandler {
	postRepository := infrastructure.NewEntPostRepo(client)
	searchTrendRepo := infrastructure.NewSearchTrendRepo(redisClient)
	postIndexer := nilPostIndexer()
	useCase := application.NewPostUseCase(postRepository, searchTrendRepo, postIndexer)
	repository := infrastructure2.NewEntFollowRepo(client)
	domainUseCase := application2.NewFeedUseCase(useCase, repository)
	feedHandler := delivery.NewFeedHandler(domainUseCase)
	return feedHandler
}

// wire.go:

func nilPostIndexer() application.PostIndexer {
	return nil
}
