// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package feed

import (
	"github.com/blog/blog-community/internal/ent"
	application2 "github.com/blog/blog-community/internal/feed/application"
	"github.com/blog/blog-community/internal/feed/delivery"
	followinfra "github.com/blog/blog-community/internal/follow/infrastructure"
	"github.com/blog/blog-community/internal/post/application"
	postinfra "github.com/blog/blog-community/internal/post/infrastructure"
)

// Injectors from wire.go:

// InitializeHandler injects feed dependencies.
func InitializeHandler(client *ent.Client) *delivery.FeedHandler {
	postRepository := postinfra.NewEntPostRepo(client)
	useCase := application.NewPostUseCase(postRepository)
	entFollowRepo := followinfra.NewEntFollowRepo(client)
	domainUseCase := application2.NewFeedUseCase(useCase, entFollowRepo)
	feedHandler := delivery.NewFeedHandler(domainUseCase)
	return feedHandler
}
