// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// CollectRecord is the predicate function for collectrecord builders.
type CollectRecord func(*sql.Selector)

// Comment is the predicate function for comment builders.
type Comment func(*sql.Selector)

// Follow is the predicate function for follow builders.
type Follow func(*sql.Selector)

// LikeRecord is the predicate function for likerecord builders.
type LikeRecord func(*sql.Selector)

// Post is the predicate function for post builders.
type Post func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
